### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by luisug** [citrix/netscaler-command-reference#1]
All links on the following page are broken.  There is a missing piece in the path, the 11.1/ is missing.  I manually edited the file for the first link, but don't know how to publish it.
https://developer-docs.citrix.com/projects/netscaler-command-reference/en/11.1

**Comment by luisug** [comment]
@ajitchelat Please review and fix this issue.

**Comment by ajitchelat** [comment]
Issue fixed with commit `ae21527`.
